In [1]:
import pandas as pd
import numpy as np

# World Value Survey 
- <b>Goal</b>: Compile relevant variables in the World Value Survey for further regression analysis
- The variable selected were based on searching "environment"
    - A103 Active/Inactive membership of environmental organization (long coverage) 
    - B001 Would give part of my income for the environment 
    - B002 Increase in taxes if used to prevent environmental pollution
    - B008 Protecting environment vs. Economic growth (long coverage) 
    - E069_14 Confidence: The Environmental Protection Movement (long coverage) 
    - S020 Year survey

In [2]:
all_data = pd.read_csv("../../data/global_WorldValueSurvey/WVS_TimeSeries_4_0.csv")
all_data

,version,doi,S002VS,S003,COUNTRY_ALPHA,COW_NUM,COW_ALPHA,S004,S006,S007,...,Y023A,Y023B,Y023C,Y024A,Y024B,Y024C,survself,tradrat5,TradAgg,SurvSAgg
0,4-0-0,doi:10.14281/18241.22,4,8,ALB,339,ALB,-4,1,80420001,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4-0-0,doi:10.14281/18241.22,4,8,ALB,339,ALB,-4,2,80420002,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4-0-0,doi:10.14281/18241.22,4,8,ALB,339,ALB,-4,3,80420003,...,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4-0-0,doi:10.14281/18241.22,4,8,ALB,339,ALB,-4,4,80420004,...,0.333333,1.000000,0.555556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4-0-0,doi:10.14281/18241.22,4,8,ALB,339,ALB,-4,5,80420005,...,0.000000,0.000000,0.222222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450864,4-0-0,doi:10.14281/18241.22,7,909,NIR,202,NIRL,-4,909070443,909070443,...,0.444444,0.222222,0.222222,0.33,0.0,0.165,0.984535,-1.182408,-2.003676,1.820009
450865,4-0-0,doi:10.14281/18241.22,7,909,NIR,202,NIRL,-4,909070444,909070444,...,1.000000,0.666667,0.777778,0.33,0.0,0.165,1.527666,0.768249,1.136881,2.803075
450866,4-0-0,doi:10.14281/18241.22,7,909,NIR,202,NIRL,-4,909070445,909070445,...,0.000000,0.000000,0.000000,0.33,0.0,0.165,0.399649,-1.394810,-2.345644,0.761364
450867,4-0-0,doi:10.14281/18241.22,7,909,NIR,202,NIRL,-4,909070446,909070446,...,1.000000,1.000000,0.444444,0.33,0.5,0.415,NaN,NaN,NaN,NaN
450868,4-0-0,doi:10.14281/18241.22,7,909,NIR,202,NIRL,-4,909070447,909070447,...,0.777778,0.555556,0.777778,0.00,1.0,0.500,0.803876,-0.468034,-0.853535,1.493016

In [29]:
select_data = all_data[["COUNTRY_ALPHA","S020","S017","A103","B001","B002","B008","E069_14"]]
select_data.to_csv("test.csv")

In [26]:
select_data.query("S020==2005").query("COUNTRY_ALPHA=='CZE'")

Empty DataFrame
Columns: [COUNTRY_ALPHA, S020, S017, A103, B001, B002, B008, E069_14]
Index: []

In [28]:
select_data["S020"].unique()

array([2002, 1998, 2014, 2005, 2018, 2011, 1997, 2006, 1999, 1995, 1991,
       1984, 2013, 2017, 2012, 1981, 1996, 2021, 2001, 2020, 1990, 2000,
       1982, 2007, 2019, 2022, 2009, 2004, 2016, 2010, 2003, 1989, 2008],
      dtype=int64)